// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'helper/product.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2108371891273071031),
    name: 'Product',
    lastPropertyId: const obx_int.IdUid(15, 2071740965247427883),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1983681352834159827),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3671115263310211885),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5892352733235045185),
        name: 'productName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8275754757775377205),
        name: 'productDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1173402057620380758),
        name: 'productPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9098219910186720979),
        name: 'totalStock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2864191299268268726),
        name: 'productUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4033412656597174363),
        name: 'expireDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4121473692285358792),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6221142370817929887),
        name: 'brand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 784422021318027093),
        name: 'sku',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 874028136027464615),
        name: 'barcode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 775901736138010858),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4500767677670841985),
        name: 'updatedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2071740965247427883),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 4945427057340568746),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2108371891273071031),
    lastIndexId: const obx_int.IdUid(1, 4945427057340568746),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Product: obx_int.EntityDefinition<Product>(
      model: _entities[0],
      toOneRelations: (Product object) => [],
      toManyRelations: (Product object) => {},
      getId: (Product object) => object.id,
      setId: (Product object, int id) {
        object.id = id;
      },
      objectToFB: (Product object, fb.Builder fbb) {
        final productNameOffset = fbb.writeString(object.productName);
        final productDescriptionOffset = fbb.writeString(
          object.productDescription,
        );
        final productUnitOffset = fbb.writeString(object.productUnit);
        final expireDateOffset = fbb.writeString(object.expireDate);
        final categoryOffset = fbb.writeString(object.category);
        final brandOffset = fbb.writeString(object.brand);
        final skuOffset = fbb.writeString(object.sku);
        final barcodeOffset = fbb.writeString(object.barcode);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final updatedAtOffset = fbb.writeString(object.updatedAt);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addOffset(2, productNameOffset);
        fbb.addOffset(3, productDescriptionOffset);
        fbb.addFloat64(4, object.productPrice);
        fbb.addInt64(5, object.totalStock);
        fbb.addOffset(6, productUnitOffset);
        fbb.addOffset(7, expireDateOffset);
        fbb.addOffset(8, categoryOffset);
        fbb.addOffset(9, brandOffset);
        fbb.addOffset(10, skuOffset);
        fbb.addOffset(11, barcodeOffset);
        fbb.addOffset(12, createdAtOffset);
        fbb.addOffset(13, updatedAtOffset);
        fbb.addOffset(14, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final productIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final productNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final productDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final productPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final totalStockParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final productUnitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final expireDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final brandParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final skuParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final barcodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final updatedAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 32, []);
        final object = Product(
          id: idParam,
          productId: productIdParam,
          productName: productNameParam,
          productDescription: productDescriptionParam,
          productPrice: productPriceParam,
          totalStock: totalStockParam,
          productUnit: productUnitParam,
          expireDate: expireDateParam,
          category: categoryParam,
          brand: brandParam,
          sku: skuParam,
          barcode: barcodeParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// See [Product.id].
  static final id = obx.QueryIntegerProperty<Product>(
    _entities[0].properties[0],
  );

  /// See [Product.productId].
  static final productId = obx.QueryIntegerProperty<Product>(
    _entities[0].properties[1],
  );

  /// See [Product.productName].
  static final productName = obx.QueryStringProperty<Product>(
    _entities[0].properties[2],
  );

  /// See [Product.productDescription].
  static final productDescription = obx.QueryStringProperty<Product>(
    _entities[0].properties[3],
  );

  /// See [Product.productPrice].
  static final productPrice = obx.QueryDoubleProperty<Product>(
    _entities[0].properties[4],
  );

  /// See [Product.totalStock].
  static final totalStock = obx.QueryIntegerProperty<Product>(
    _entities[0].properties[5],
  );

  /// See [Product.productUnit].
  static final productUnit = obx.QueryStringProperty<Product>(
    _entities[0].properties[6],
  );

  /// See [Product.expireDate].
  static final expireDate = obx.QueryStringProperty<Product>(
    _entities[0].properties[7],
  );

  /// See [Product.category].
  static final category = obx.QueryStringProperty<Product>(
    _entities[0].properties[8],
  );

  /// See [Product.brand].
  static final brand = obx.QueryStringProperty<Product>(
    _entities[0].properties[9],
  );

  /// See [Product.sku].
  static final sku = obx.QueryStringProperty<Product>(
    _entities[0].properties[10],
  );

  /// See [Product.barcode].
  static final barcode = obx.QueryStringProperty<Product>(
    _entities[0].properties[11],
  );

  /// See [Product.createdAt].
  static final createdAt = obx.QueryStringProperty<Product>(
    _entities[0].properties[12],
  );

  /// See [Product.updatedAt].
  static final updatedAt = obx.QueryStringProperty<Product>(
    _entities[0].properties[13],
  );

  /// See [Product.embedding].
  static final embedding = obx.QueryHnswProperty<Product>(
    _entities[0].properties[14],
  );
}
